"""empty message

Revision ID: 4f257356c65b
Revises: a686804db542
Create Date: 2024-05-24 15:05:33.760302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f257356c65b'
down_revision = 'a686804db542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_log',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('liter', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuel_log')
    # ### end Alembic commands ###
