version: "3.0"

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:      
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  app:
    container_name: fuelmeter
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

volumes:
  postgres_data:
    driver: postgres
